"""Add OcrBase, OcrDetails, and is_ocr_extracted field

Revision ID: 7a0f6f9e0c54
Revises: e48efc91de52
Create Date: 2025-03-08 06:00:23.483629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0f6f9e0c54'
down_revision = 'e48efc91de52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_base',
    sa.Column('ocr_base_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], ),
    sa.PrimaryKeyConstraint('ocr_base_id')
    )
    op.create_table('ocr_details',
    sa.Column('ocr_details_id', sa.Integer(), nullable=False),
    sa.Column('ocr_base_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=100), nullable=False),
    sa.Column('text_value', sa.String(length=255), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ocr_base_id'], ['ocr_base.ocr_base_id'], ),
    sa.PrimaryKeyConstraint('ocr_details_id')
    )
    op.drop_table('ocr_data')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ocr_extracted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('is_ocr_extracted')

    op.create_table('ocr_data',
    sa.Column('ocr_data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('text_value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('normalized_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.receipt_id'], name='ocr_data_receipt_id_fkey'),
    sa.PrimaryKeyConstraint('ocr_data_id', name='ocr_data_pkey')
    )
    op.drop_table('ocr_details')
    op.drop_table('ocr_base')
    # ### end Alembic commands ###
