"""receipt and ocr relationship updated2

Revision ID: e48efc91de52
Revises: 4b7db92ce734
Create Date: 2025-03-04 04:48:23.517725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e48efc91de52'
down_revision = '4b7db92ce734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('ocr_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
